spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300,127.0.0.1:9301,127.0.0.1:9302
      cluster-name: my-application #es6
server:
  port: 8888